x/tax/spec/03_state_transitions.md, x/tax/spec/04_begin_block.md, x/tax/spec/05_events.md, x/tax/spec/06_params.md
- We decided to use `ParameterChangeProposal` instead of creating a new separate ProposalType for adding, modifying, and deleting Taxes. Update content for this.
- Add `tax_collected` event type
- Add `Begin-Block` logic
- Add `Validity Checks` for Taxes
=> Update Spec with logic explain and validity checklist

app/app.go, go.mod, go.sum
=> Bump Cosmos-SDK to v0.43.0-rc3

.github/ISSUE_TEMPLATE/bug-report.md, .github/ISSUE_TEMPLATE/feature-request.md, .github/PULL_REQUEST_TEMPLATE.md, .pre-commit-config.yaml, TECHNICAL-SETUP.md
Ref 
- https://github.com/tendermint/tax/issues/1
- https://github.com/tendermint/farming
=> Add github templates and precommit

go.mod, go.sum
=> bump cosmos-sdk to v0.43.0

app/app.go, app/app_test.go, x/tax/module.go
=> fix: solve module, simapp issues

.gitignore, x/budget/spec/README.md
=> fix: rename module to budget

README.md, docs/How-To/README.md, docs/How-To/api/README.md, docs/How-To/cli/README.md, docs/README.md, docs/Tutorials/README.md
This PR fixes incorrect words and typos and update descriptions to provide better context. It also updates definition of budget module in `README.md` file 
---
=> docs: fix incorrect words and typos and update descriptions

README.md, docs/Tutorials/demo/README.md
=> docs: update broken links

.github/.codecov.yml
=> feat: disable codecov on patch

docs/How-To/cli/README.md
This PR is a quick and minor fix for demo documentation. It is related to https://github.com/tendermint/farming/pull/183
---
=> docs: specify which module is used for module name in demo

x/budget/keeper/budget.go, x/budget/keeper/budget_test.go, x/budget/keeper/keeper_test.go, x/budget/types/budget.go
Related #58 , Add govHandler for paramChangeProposal to test budget params
And Current `Expire()` function only checks `EndTime` is not expired, so on this PR, fix `Expire()` to `Collectible` for checks with `startTime`, `endTime` both 
- #58 
---
=> fix: Add govHandler on testcode for budget proposal and Fix Expired rule

x/budget/spec/README.md
closes part of #71
- 
---
- [ x] Linked to Github issue with discussion and accepted design OR link to spec that describes this work.
=> docs: budget Update README.md

x/budget/spec/02_state.md
closes part of #71
- 
---
- [ x] Appropriate labels applied
- [ x] Linked to Github issue with discussion and accepted design OR link to spec that describes this work.
- [x ] Code follows the [module structure standards](https://github.com/cosmos/cosmos-sdk/blob/master/docs/building-modules/structure.md).
- [ x] Updated relevant documentation (`docs/`) or specification (`x/<module>/spec/`)
=> docs: budget update state edits

x/budget/spec/03_state_transitions.md
- 
---
- [ x] Appropriate labels applied
- [ x] Linked to Github issue with discussion and accepted design OR link to spec that describes this work.
- [x ] Code follows the [module structure standards](https://github.com/cosmos/cosmos-sdk/blob/master/docs/building-modules/structure.md).
- [ x] Updated relevant documentation (`docs/`) or specification (`x/<module>/spec/`)
=> docs: Update budget 03_state_transitions.md

x/budget/spec/04_begin_block.md
- 
---
- [x ] Targeted PR against correct branch
- [x ] Code follows the [module structure standards](https://github.com/cosmos/cosmos-sdk/blob/master/docs/building-modules/structure.md).
=> docs: budget Update 04_begin_block.md

x/budget/spec/05_events.md
closes park of #71 
- 
---
- [ x] Code follows the [module structure standards](https://github.com/cosmos/cosmos-sdk/blob/master/docs/building-modules/structure.md).
=> docs: budget Update 05_events.md

x/budget/spec/06_params.md
- 
---
- [x ] Targeted PR against correct branch
- [x ] Code follows the [module structure standards](https://github.com/cosmos/cosmos-sdk/blob/master/docs/building-modules/structure.md).
=> docs: budget Update 06_params.md

docs/Tutorials/localnet/README.md
minor edits
- 
---
- [ x] Code follows the [module structure standards](https://github.com/cosmos/cosmos-sdk/blob/master/docs/building-modules/structure.md).
=> docs: localnet readme

docs/How-To/api/README.md
API readme
- 
---
- [x ] Targeted PR against correct branch
- [ x] Code follows the [module structure standards](https://github.com/cosmos/cosmos-sdk/blob/master/docs/building-modules/structure.md).
- [ x] Updated relevant documentation (`docs/`) or specification (`x/<module>/spec/`)
=> docs: api readme edits

README.md, go.mod, go.sum, x/budget/types/genesis_test.go
- https://github.com/cosmos/cosmos-sdk/compare/v0.44.3...v0.44.5
---
=> build: bump cosmos-sdk to v0.44.5

CHANGELOG.md, x/budget/keeper/genesis.go, x/budget/keeper/genesis_test.go, x/budget/simulation/genesis.go, x/budget/simulation/proposals.go
=> fix: init budgets to avoid nil slice on genesis

app/sim_test.go, x/budget/keeper/budget.go, x/budget/types/budget.go, x/budget/types/params.go
=> fix: iterating budgetsBySourceMap deterministic
